name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up C++ environment
      uses: cpp-actions/setup-cpp@v1

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++ libboost-all-dev

    - name: Install Crow and Dependencies
      run: |
        mkdir -p dependencies
        cd dependencies
        git clone https://github.com/ipkn/crow.git
        cd crow
        sed -i 's/return GET_IO_SERVICE(raw_socket());/return socket_.get_executor().context();/' include/crow/socket_adaptors.h
        mkdir build
        cd build
        cmake ..
        make -j$(nproc)
    
    - name: Build the project
      run: |
        mkdir build
        cd build
        cmake ..
        make -j$(nproc)

    - name: Run Tests
      run: |
        cd build
        ctest

