name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install g++
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Install Conan
        run: pip install conan

      - name: Detect Conan profile
        run: conan profile detect --force

      - name: Install dependencies
        run: |
          conan install . --output-folder=build --build=missing
          
      - name: List build directory
        run: ls -l build/build/Release/generators

      - name: Build project
        run: |
          cd build
          cmake .. -DCMAKE_TOOLCHAIN_FILE=build/build/Release/generators/conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release
          cmake --build .
          make

      - name: Additional steps
        run: |
          echo "Add other actions to build, test, and deploy your project."
